# Generated by Django 3.0.3 on 2020-02-26 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 2, 26, 15, 44, 14, 399722, tzinfo=utc))),
            ],
        ),
    ]
