# Generated by Django 3.0.3 on 2020-02-26 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 19, 53, 783232, tzinfo=utc)),
        ),
    ]
