# Generated by Django 3.0.4 on 2020-03-17 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 14, 19, 56, 532327, tzinfo=utc)),
        ),
    ]
